name: Sync-Images-to-DockerHub-Example
run-name: ${{ github.actor }} is Sync Images to DockerHub.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # 允许手动触发

jobs:
  syncimages:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码仓库中的内容

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 设置 Docker Buildx，必要时可以进行跨平台构建

      - name: Log in to Alibaba Cloud Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 从 GitHub Secrets 获取用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # 从 GitHub Secrets 获取密码
          registry: registry.cn-hangzhou.aliyuncs.com  # 登录到阿里云 Docker 仓库

      # 使用 Skopeo 工具同步镜像
      - name: Sync Nginx Image with Skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo  # 安装 Skopeo 工具
          skopeo copy docker://docker.io/nginx:alpine docker://registry.cn-hangzhou.aliyuncs.com/aliang11/3011549907/nginx:alpine

      - name: Sync Alpine Image with Skopeo
        run: |
          skopeo copy docker://docker.io/alpine:latest docker://registry.cn-hangzhou.aliyuncs.com/aliang11/3011549907/alpine:latest

      - name: Sync Golang Image with Skopeo
        run: |
          skopeo copy docker://docker.io/golang:1.23 docker://registry.cn-hangzhou.aliyuncs.com/aliang11/3011549907/golang:1.23

      - name: Sync Node.js Image with Skopeo
        run: |
          skopeo copy docker://docker.io/node:16-alpine docker://registry.cn-hangzhou.aliyuncs.com/aliang11/3011549907/node:16-alpine

      - name: Sync MySQL Image with Skopeo
        run: |
          skopeo copy docker://docker.io/mysql:latest docker://registry.cn-hangzhou.aliyuncs.com/aliang11/3011549907/mysql:latest

      - name: Sync Redis Image with Skopeo
        run: |
          skopeo copy docker://docker.io/redis:latest docker://registry.cn-hangzhou.aliyuncs.com/aliang11/3011549907/redis:latest

      - name: Sync PostgreSQL Image with Skopeo
        run: |
          skopeo copy docker://docker.io/postgres:latest docker://registry.cn-hangzhou.aliyuncs.com/aliang11/3011549907/postgres:latest

      - name: Sync MongoDB Image with Skopeo
        run: |
          skopeo copy docker://docker.io/mongo:latest docker://registry.cn-hangzhou.aliyuncs.com/aliang11/3011549907/mongo:latest

      - name: Sync Python Image with Skopeo
        run: |
          skopeo copy docker://docker.io/python:3.10-alpine docker://registry.cn-hangzhou.aliyuncs.com/aliang11/3011549907/python:3.10-alpine

      - name: Sync OpenJDK Image with Skopeo
        run: |
          skopeo copy docker://docker.io/openjdk:17-alpine docker://registry.cn-hangzhou.aliyuncs.com/aliang11/3011549907/openjdk:17-alpine
